# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:

# workflows
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    cron: "*/1 * * * *"
  groups:
    all:
      patterns:
      - "minor"
      - "patch"
